using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;

namespace PoE2RouteSetup;

public static class LiveSplitFiles
{
    private static readonly Regex LiveSplitPathRegex = new(
        "System\\.IO\\.Path\\.Combine\\(vars\\.liveSplitDir,\\s*\"([^\"]+)\"\\)",
        RegexOptions.Compiled);

    private static readonly Regex ManualPauseDefaultRegex = new(
        "settings\\.Add\\(\"manualPauseRemoval\",\\s*(?:true|false),",
        RegexOptions.Compiled);

    private static readonly Regex AutoStartDefaultRegex = new(
        "settings\\.Add\\(\"autoStart\",\\s*(?:true|false),",
        RegexOptions.Compiled);

    private static readonly Regex RouteStartDirectiveRegex = new(
        "(?im)^(\\s*@start=)[^\\r\\n#]+",
        RegexOptions.Compiled);

    public static string RewriteRuntimePaths(string aslText, string targetDir)
    {
        return LiveSplitPathRegex.Replace(aslText, match =>
        {
            var path = Path.Combine(targetDir, match.Groups[1].Value);
            return QuoteCSharp(path);
        });
    }

    public static bool SupportsRuntimeStartPolicy(string aslText) =>
        aslText.Contains("vars.startAreaId", StringComparison.Ordinal)
        && aslText.Contains("@start", StringComparison.OrdinalIgnoreCase);

    public static string ApplyAutoStartOption(string aslText, bool autoStart)
    {
        if (!AutoStartDefaultRegex.IsMatch(aslText))
        {
            if (autoStart)
                throw new InvalidOperationException("The selected autosplitter does not expose the expected auto-start setting.");
            return aslText;
        }

        var replacement = "settings.Add(\"autoStart\", " + (autoStart ? "true" : "false") + ",";
        return AutoStartDefaultRegex.Replace(aslText, replacement, 1);
    }

    public static string ApplyRouteStartPolicy(string runtimeText, StartPolicy startPolicy)
    {
        if (!RouteStartDirectiveRegex.IsMatch(runtimeText))
            return runtimeText;

        return RouteStartDirectiveRegex.Replace(
            runtimeText,
            match => match.Groups[1].Value + startPolicy.RouteDirectiveValue,
            1);
    }

    /// <summary>
    /// Adds a setup-generated area-entry start reader to autosplitters that do not already
    /// support a configurable @start area. The reader is independent from every route,
    /// BossWatcher, and Game Time Client.txt reader so start detection cannot consume events
    /// needed by the rest of the autosplitter.
    /// </summary>
    public static string ApplyGeneratedZoneStartPolicy(string aslText, StartPolicy startPolicy)
    {
        // Disable the older hard-coded Riverbank start path. The generated setup start path
        // below becomes authoritative for Manual, Riverbank, and arbitrary zone-entry starts.
        if (AutoStartDefaultRegex.IsMatch(aslText))
        {
            aslText = AutoStartDefaultRegex.Replace(aslText, "settings.Add(\"autoStart\", false,", 1);
            aslText = aslText.Replace("settings[\"autoStart\"]", "false", StringComparison.Ordinal);
        }

        var enabled = startPolicy.IsAutomatic ? "true" : "false";
        var areaId = startPolicy.AreaId ?? "";
        var areaName = startPolicy.AreaName ?? "";

        var startupCode = string.Join(Environment.NewLine, new[]
        {
            "    // SETUP_START_POLICY_BEGIN - generated by PoE2RouteSetup",
            $"    vars.setupStartEnabled = {enabled};",
            $"    vars.setupStartAreaId = {QuoteCSharp(areaId)};",
            $"    vars.setupStartAreaName = {QuoteCSharp(areaName)};",
            "    vars.setupStartReader = null;",
            "    vars.setupStartTrigger = false;",
            "    vars.setupStartRiverbankArmed = false;",
            "    // SETUP_START_POLICY_END"
        });
        aslText = InsertAfterActionOpen(aslText, "startup", startupCode, required: true);

        var initCode = string.Join(Environment.NewLine, new[]
        {
            "    // SETUP_START_READER_INIT_BEGIN",
            "    try { if (vars.setupStartReader != null) vars.setupStartReader.Close(); } catch {}",
            "    vars.setupStartReader = null;",
            "    vars.setupStartTrigger = false;",
            "    vars.setupStartRiverbankArmed = false;",
            "    if (vars.setupStartEnabled)",
            "    {",
            "        try",
            "        {",
            "            string setupStartGameDir = System.IO.Path.GetDirectoryName(modules.First().FileName);",
            "            string setupStartClientPath = System.IO.Path.Combine(setupStartGameDir, \"logs\", \"Client.txt\");",
            "            var setupStartFs = new System.IO.FileStream(setupStartClientPath, System.IO.FileMode.Open, System.IO.FileAccess.Read, System.IO.FileShare.ReadWrite);",
            "            setupStartFs.Seek(0, System.IO.SeekOrigin.End);",
            "            vars.setupStartReader = new System.IO.StreamReader(setupStartFs);",
            "        }",
            "        catch { vars.setupStartReader = null; }",
            "    }",
            "    // SETUP_START_READER_INIT_END"
        });
        aslText = InsertAfterActionOpen(aslText, "init", initCode, required: true);

        var internalNeedle = QuoteCSharp("area \"" + areaId + "\"");
        var enteredNeedle = QuoteCSharp("You have entered " + areaName + ".");
        var riverbankInternalNeedle = QuoteCSharp("area \"G1_1\"");
        var riverbankEnteredNeedle = QuoteCSharp("You have entered The Riverbank.");
        var woundedNeedle = QuoteCSharp("Wounded Man: Reach... Clearfell... Find the Miller...");

        var updateLines = new List<string>
        {
            "    // SETUP_START_READER_UPDATE_BEGIN",
            "    vars.setupStartTrigger = false;",
            "    if (vars.setupStartReader != null)",
            "    {",
            "        int setupStartProcessed = 0;",
            "        string setupStartLine = null;",
            "        while (setupStartProcessed < 500 && (setupStartLine = vars.setupStartReader.ReadLine()) != null)",
            "        {",
            "            setupStartProcessed++;",
            "",
            "            // Always drain the independent reader while a run is active so a reset",
            "            // cannot replay an old zone entry and immediately restart the timer.",
            "            if (timer.CurrentPhase != LiveSplit.Model.TimerPhase.NotRunning) continue;",
            "",
            "            if (System.String.Equals(vars.setupStartAreaId, \"G1_1\", System.StringComparison.OrdinalIgnoreCase))",
            "            {",
            $"                bool setupRiverbankInternalEntry = setupStartLine.IndexOf(\"Generating level\", System.StringComparison.OrdinalIgnoreCase) >= 0",
            $"                    && setupStartLine.IndexOf({riverbankInternalNeedle}, System.StringComparison.OrdinalIgnoreCase) >= 0;",
            $"                bool setupRiverbankEntry = setupRiverbankInternalEntry",
            $"                    || setupStartLine.IndexOf({riverbankEnteredNeedle}, System.StringComparison.OrdinalIgnoreCase) >= 0;",
            "                if (setupRiverbankEntry)",
            "                {",
            "                    vars.setupStartRiverbankArmed = true;",
            "                    continue;",
            "                }",
            "",
            $"                if (vars.setupStartRiverbankArmed && setupStartLine.IndexOf({woundedNeedle}, System.StringComparison.OrdinalIgnoreCase) >= 0)",
            "                {",
            "                    vars.setupStartTrigger = true;",
            "                    vars.setupStartRiverbankArmed = false;",
            "                    break;",
            "                }",
            "            }",
            "            else if (vars.setupStartAreaId != \"\")",
            "            {",
            $"                bool setupInternalEntry = setupStartLine.IndexOf(\"Generating level\", System.StringComparison.OrdinalIgnoreCase) >= 0",
            $"                    && setupStartLine.IndexOf({internalNeedle}, System.StringComparison.OrdinalIgnoreCase) >= 0;",
            $"                bool setupNamedEntry = setupStartLine.IndexOf({enteredNeedle}, System.StringComparison.OrdinalIgnoreCase) >= 0;",
            "                if (setupInternalEntry || setupNamedEntry)",
            "                {",
            "                    vars.setupStartTrigger = true;",
            "                    break;",
            "                }",
            "            }",
            "        }",
            "    }"
        };

        // Ordered/Flexible exploration and Level Race also own a Client.txt tail reader.
        // While an automatic setup start is waiting, keep that original reader at EOF but
        // do not let it mutate split state. The selected start transition is therefore a
        // clean timing boundary rather than a queued zero-time/pre-start split.
        if (aslText.Contains("vars.reader", StringComparison.Ordinal))
        {
            updateLines.AddRange(new[]
            {
                "    if (vars.setupStartEnabled && timer.CurrentPhase == LiveSplit.Model.TimerPhase.NotRunning)",
                "    {",
                "        if (vars.reader != null)",
                "        {",
                "            try { while (vars.reader.ReadLine() != null) {} } catch {}",
                "        }",
                "        return true;",
                "    }"
            });
        }

        updateLines.Add("    // SETUP_START_READER_UPDATE_END");
        var updateCode = string.Join(Environment.NewLine, updateLines);
        aslText = InsertAfterActionOpen(aslText, "update", updateCode, required: true);

        const string startCode = "    if (vars.setupStartEnabled && vars.setupStartTrigger) return true; // SETUP_START_POLICY";
        if (HasAction(aslText, "start"))
        {
            aslText = InsertAfterActionOpen(aslText, "start", startCode, required: true);
        }
        else
        {
            var newline = DetectNewline(aslText);
            var startBlock = "start" + newline + "{" + newline + startCode + newline + "}" + newline + newline;
            aslText = InsertBeforeAction(aslText, "split", startBlock);
        }

        // Flexible exploration has one fewer timed area row because its start area is
        // implicitly satisfied. Preserve that invariant for Riverbank or any selected
        // zone that is part of the enabled unordered area pool.
        if (aslText.Contains("vars.completedAreaIds", StringComparison.Ordinal)
            && aslText.Contains("vars.subgroupCompleted", StringComparison.Ordinal)
            && HasAction(aslText, "onStart"))
        {
            var flexibleOnStartCode = string.Join(Environment.NewLine, new[]
            {
                "    // SETUP_START_FLEXIBLE_IMPLICIT_OBJECTIVE_BEGIN",
                "    if (vars.setupStartEnabled",
                "        && vars.setupStartAreaId != \"\"",
                "        && vars.enabledAreaIds.Contains(vars.setupStartAreaId)",
                "        && !vars.completedAreaIds.Contains(vars.setupStartAreaId))",
                "    {",
                "        vars.completedAreaIds.Add(vars.setupStartAreaId);",
                "        string setupStartSubgroup = vars.areaSubgroup.ContainsKey(vars.setupStartAreaId) ? vars.areaSubgroup[vars.setupStartAreaId] : \"\";",
                "        if (setupStartSubgroup != \"\")",
                "            vars.subgroupCompleted[setupStartSubgroup] = vars.subgroupCompleted[setupStartSubgroup] + 1;",
                "    }",
                "    // SETUP_START_FLEXIBLE_IMPLICIT_OBJECTIVE_END"
            });
            aslText = InsertAfterActionOpen(aslText, "onStart", flexibleOnStartCode, required: true);
        }

        if (HasAction(aslText, "onReset"))
        {
            const string resetCode = "    vars.setupStartTrigger = false; vars.setupStartRiverbankArmed = false; // SETUP_START_POLICY_RESET";
            aslText = InsertAfterActionOpen(aslText, "onReset", resetCode, required: true);
        }

        return aslText;
    }

    public static string ApplyGameTimeOptions(string aslText, bool excludeManualPauses)
    {
        if (!ManualPauseDefaultRegex.IsMatch(aslText))
            throw new InvalidOperationException("The selected ASL does not expose the expected manual-pause Game Time setting.");

        var replacement = "settings.Add(\"manualPauseRemoval\", " + (excludeManualPauses ? "true" : "false") + ",";
        return ManualPauseDefaultRegex.Replace(aslText, replacement, 1);
    }

    public static string PrependRiverbankRouteEntry(string runtimeText)
    {
        var newline = runtimeText.Contains("\r\n", StringComparison.Ordinal) ? "\r\n" : "\n";
        var lines = Regex.Split(runtimeText, "\r\n|\n").ToList();

        foreach (var raw in lines)
        {
            var line = raw;
            var hash = line.IndexOf('#');
            if (hash >= 0) line = line[..hash];
            line = line.Trim();
            if (line.Length == 0) continue;
            if (line.Equals("G1_1", StringComparison.OrdinalIgnoreCase))
                return runtimeText;
            break;
        }

        var insertAt = 0;
        while (insertAt < lines.Count)
        {
            var trimmed = lines[insertAt].Trim();
            if (trimmed.Length > 0 && !trimmed.StartsWith("#", StringComparison.Ordinal))
                break;
            insertAt++;
        }

        lines.Insert(insertAt, "G1_1                                   # The Riverbank");
        return string.Join(newline, lines);
    }

    public static void WritePresetSplits(string sourcePath, string outputPath, bool prependRiverbank)
    {
        if (!prependRiverbank)
        {
            File.Copy(sourcePath, outputPath, true);
            return;
        }

        var run = XDocument.Load(sourcePath, LoadOptions.PreserveWhitespace);
        var segments = run.Root?.Element("Segments")
            ?? throw new InvalidOperationException("The selected .lss file does not contain a Segments element.");

        var firstName = segments.Elements("Segment").FirstOrDefault()?.Element("Name")?.Value ?? "";
        if (!firstName.Equals("The Riverbank", StringComparison.OrdinalIgnoreCase))
            segments.AddFirst(CreateSegment("The Riverbank"));

        run.Save(outputPath);
    }

    public static void AdjustAreaChecklistSplits(string outputPath, string runtimeText)
    {
        string startId = "";
        var objectives = new List<string>();

        foreach (var raw in Regex.Split(runtimeText, "\r\n|\n"))
        {
            var line = raw;
            var hash = line.IndexOf('#');
            if (hash >= 0) line = line[..hash];
            line = line.Trim();
            if (line.Length == 0) continue;

            if (line.StartsWith("@start=", StringComparison.OrdinalIgnoreCase))
            {
                var value = line[7..].Trim();
                startId = value.Equals("manual", StringComparison.OrdinalIgnoreCase) ? "" : value;
                continue;
            }
            if (line.StartsWith("@", StringComparison.Ordinal)) continue;
            objectives.Add(line);
        }

        var implicitStart = startId.Length > 0 && objectives.Contains(startId, StringComparer.OrdinalIgnoreCase) ? 1 : 0;
        var expectedCount = objectives.Count - implicitStart;
        if (expectedCount < 1)
            throw new InvalidOperationException("The Area Checklist preset must contain at least one timed split after applying the start policy.");

        var run = XDocument.Load(outputPath, LoadOptions.PreserveWhitespace);
        var segments = run.Root?.Element("Segments")
            ?? throw new InvalidOperationException("The selected .lss file does not contain a Segments element.");
        var list = segments.Elements("Segment").ToList();

        while (list.Count > expectedCount)
        {
            list[^1].Remove();
            list.RemoveAt(list.Count - 1);
        }
        while (list.Count < expectedCount)
        {
            var segment = CreateSegment($"Objective {list.Count + 1:D3}");
            segments.Add(segment);
            list.Add(segment);
        }

        // Area Checklist layouts use generic objective rows that are renamed dynamically.
        // Keep numbering contiguous after a row is added or removed for a changed start area.
        for (var i = 0; i < list.Count; i++)
        {
            var name = list[i].Element("Name");
            if (name is not null && name.Value.StartsWith("Objective ", StringComparison.OrdinalIgnoreCase))
                name.Value = $"Objective {i + 1:D3}";
        }

        run.Save(outputPath);
    }

    public static void WritePremadeSplits(string outputPath, IReadOnlyList<RouteEntry> objectives, string categoryName)
    {
        var segments = new XElement("Segments");
        foreach (var objective in objectives)
            segments.Add(CreateSegment(objective.Name));

        var run = new XDocument(
            new XDeclaration("1.0", "utf-8", null),
            new XElement("Run", new XAttribute("version", "1.7.0"),
                new XElement("GameIcon"),
                new XElement("GameName", "Path of Exile 2"),
                new XElement("CategoryName", categoryName),
                new XElement("Metadata",
                    new XElement("Run", new XAttribute("id", "")),
                    new XElement("Platform", new XAttribute("usesEmulator", "False"), "PC"),
                    new XElement("Region"),
                    new XElement("Variables")),
                new XElement("Offset", "00:00:00"),
                new XElement("AttemptCount", 0),
                segments));
        run.Save(outputPath);
    }

    public static void WriteCustomSplits(string outputPath, IReadOnlyList<RouteEntry> objectives)
    {
        var segments = new XElement("Segments");
        for (var i = 0; i < objectives.Count; i++)
        {
            var objective = objectives[i];
            var typeLabel = objective.Type.ToLowerInvariant() switch
            {
                "boss" => "Boss",
                "bossocc" => "Repeated Boss",
                "bossall" => "Boss Pair",
                "bossany" => "Dynamic Boss",
                "bossnth" => "Nth Dynamic Boss",
                "bossslot" => "Dynamic Boss",
                "level" => "Level",
                "areaocc" => "Repeated Area",
                _ => "Area"
            };
            segments.Add(CreateSegment($"{objective.Name} [{typeLabel}]"));
        }

        var run = new XDocument(
            new XDeclaration("1.0", "utf-8", null),
            new XElement("Run", new XAttribute("version", "1.7.0"),
                new XElement("GameIcon"),
                new XElement("GameName", "Path of Exile 2"),
                new XElement("CategoryName", "Custom Route - Areas + Bosses + Levels"),
                new XElement("Metadata",
                    new XElement("Run", new XAttribute("id", "")),
                    new XElement("Platform", new XAttribute("usesEmulator", "False"), "PC"),
                    new XElement("Region"),
                    new XElement("Variables")),
                new XElement("Offset", "00:00:00"),
                new XElement("AttemptCount", 0),
                segments));
        run.Save(outputPath);
    }

    private static XElement CreateSegment(string name) => new(
        "Segment",
        new XElement("Name", name),
        new XElement("Icon"),
        new XElement("SplitTimes", new XElement("SplitTime", new XAttribute("name", "Personal Best"))),
        new XElement("BestSegmentTime"),
        new XElement("SegmentHistory"));

    private static bool HasAction(string text, string action) =>
        Regex.IsMatch(text, $@"(?m)^\s*{Regex.Escape(action)}\s*(?:\r?\n\s*)?\{{");

    private static string InsertAfterActionOpen(string text, string action, string code, bool required)
    {
        var regex = new Regex($@"(?m)^\s*{Regex.Escape(action)}\s*(?:\r?\n\s*)?\{{", RegexOptions.Compiled);
        var match = regex.Match(text);
        if (!match.Success)
        {
            if (required) throw new InvalidOperationException($"Could not locate the {action} action in the selected ASL.");
            return text;
        }

        var newline = DetectNewline(text);
        return text.Insert(match.Index + match.Length, newline + code);
    }

    private static string InsertBeforeAction(string text, string action, string block)
    {
        var regex = new Regex($@"(?m)^\s*{Regex.Escape(action)}\s*(?:\r?\n\s*)?\{{", RegexOptions.Compiled);
        var match = regex.Match(text);
        if (!match.Success)
            throw new InvalidOperationException($"Could not locate the {action} action in the selected ASL.");
        return text.Insert(match.Index, block);
    }

    private static string DetectNewline(string text) => text.Contains("\r\n", StringComparison.Ordinal) ? "\r\n" : "\n";
    private static string QuoteCSharp(string value) => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
